graphql:
  packages: "uk.co.ivli.bplogger.graphql"
  playground:
    enabled: true

server:
  port: 8008
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local-bp-logger